### ISSUE TITLE
Unsubscribe only specific callback

### ISSUE THREAD

**Issue by qwelias** [olesku/eventhub-jsclient#25]
In some use cases it is possible to have multiple concurrent subscriptions to the same topic.
Unsubscribing one currently unsubscribes all of them.

In JS it's a common practice to have an ability to unsub only specific listener, e.g. https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener and https://nodejs.org/dist/latest-v14.x/docs/api/events.html#events_emitter_removelistener_eventname_listener to avoid it.

**Comment by olesku** [comment]
Thanks for your input. I think this might be a good change to implement, but it will require some fundamental changes to both eventhub and the javascript library. It also would be hard to implement without breaking backwards compatibility, however I think this is a improvement worth it.

**Comment by qwelias** [comment]
Not an issue since the server does not support multiple subscriptions and the client does not allow it either.
